export const userStatsMockup = {
  biggest_ride_distance: 176757,
  biggest_climb_elevation_gain: 1338.6,
  recent_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_ride_totals: {
    count: 1633,
    distance: 41324935,
    moving_time: 6414430,
    elapsed_time: 9112946,
    elevation_gain: 393409,
  },
  recent_run_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_run_totals: {
    count: 12,
    distance: 69419,
    moving_time: 24801,
    elapsed_time: 21440933,
    elevation_gain: 451,
  },
  recent_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
  },
  ytd_ride_totals: {
    count: 276,
    distance: 5289096,
    moving_time: 773529,
    elapsed_time: 1329596,
    elevation_gain: 29434,
  },
  ytd_run_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
  },
  ytd_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
  },
};
