export const userMockup = {
  id: 14592553,
  username: "lukasz_romanowski",
  resource_state: 3,
  firstname: "Łukasz",
  lastname: "Romanowski",
  bio: "",
  city: "Kraków",
  state: "Lesser Poland Voivodeship",
  country: "Poland",
  sex: "M",
  premium: false,
  summit: false,
  created_at: "2016-04-16T11:28:38Z",
  updated_at: "2022-12-19T21:35:36Z",
  badge_type_id: 0,
  weight: 72,
  profile_medium:
    "https://dgalywyr863hv.cloudfront.net/pictures/athletes/14592553/9923464/2/medium.jpg",
  profile:
    "https://dgalywyr863hv.cloudfront.net/pictures/athletes/14592553/9923464/2/large.jpg",
  friend: null,
  follower: null,
  blocked: false,
  can_follow: true,
  follower_count: 45,
  friend_count: 16,
  mutual_friend_count: 0,
  athlete_type: 0,
  date_preference: "%m/%d/%Y",
  measurement_preference: "meters",
  clubs: [
    {
      id: 38013,
      resource_state: 2,
      name: "GCN",
      profile_medium:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/38013/1033989/3/medium.jpg",
      profile:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/38013/1033989/3/large.jpg",
      cover_photo:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/38013/5381044/15/large.jpg",
      cover_photo_small:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/38013/5381044/15/small.jpg",
      activity_types: [
        "Handcycle",
        "EBikeRide",
        "VirtualRide",
        "Velomobile",
        "Ride",
      ],
      activity_types_icon: "sports_bike_normal",
      dimensions: [
        "distance",
        "num_activities",
        "best_activities_distance",
        "velocity",
        "elev_gain",
        "moving_time",
      ],
      sport_type: "cycling",
      city: "Bath",
      state: "England",
      country: "United Kingdom",
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: "globalcyclingnetwork",
      membership: "member",
      admin: false,
      owner: false,
    },
    {
      id: 104733,
      resource_state: 2,
      name: "Zwift",
      profile_medium:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/104733/1834766/4/medium.jpg",
      profile:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/104733/1834766/4/large.jpg",
      cover_photo:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/104733/4520795/36/large.jpg",
      cover_photo_small:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/104733/4520795/36/small.jpg",
      activity_types: [
        "Handcycle",
        "EBikeRide",
        "VirtualRide",
        "Velomobile",
        "Ride",
      ],
      activity_types_icon: "sports_bike_normal",
      dimensions: [
        "distance",
        "num_activities",
        "best_activities_distance",
        "velocity",
        "elev_gain",
        "moving_time",
      ],
      sport_type: "cycling",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: "gozwift",
      membership: "member",
      admin: false,
      owner: false,
    },
    {
      id: 185443,
      resource_state: 2,
      name: "Cichy Kącik Kraków",
      profile_medium:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/185443/3943762/2/medium.jpg",
      profile:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/185443/3943762/2/large.jpg",
      cover_photo:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/185443/4530028/3/large.jpg",
      cover_photo_small:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/185443/4530028/3/small.jpg",
      activity_types: [
        "Handcycle",
        "EBikeRide",
        "VirtualRide",
        "Velomobile",
        "Ride",
      ],
      activity_types_icon: "sports_bike_normal",
      dimensions: [
        "distance",
        "num_activities",
        "best_activities_distance",
        "velocity",
        "elev_gain",
        "moving_time",
      ],
      sport_type: "cycling",
      city: "Kraków",
      state: "małopolskie",
      country: "Polska",
      private: true,
      member_count: 0,
      featured: false,
      verified: false,
      url: "cichykacik",
      membership: "member",
      admin: false,
      owner: false,
    },
    {
      id: 202024,
      resource_state: 2,
      name: "OTR Kraków",
      profile_medium:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/202024/4399172/1/medium.jpg",
      profile:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/202024/4399172/1/large.jpg",
      cover_photo:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/202024/4448049/7/large.jpg",
      cover_photo_small:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/202024/4448049/7/small.jpg",
      activity_types: [
        "Handcycle",
        "EBikeRide",
        "VirtualRide",
        "Velomobile",
        "Ride",
      ],
      activity_types_icon: "sports_bike_normal",
      dimensions: [
        "distance",
        "num_activities",
        "best_activities_distance",
        "velocity",
        "elev_gain",
        "moving_time",
      ],
      sport_type: "cycling",
      city: "Kraków",
      state: "małopolskie",
      country: "Polska",
      private: true,
      member_count: 0,
      featured: false,
      verified: false,
      url: "otr-krakow",
      membership: "member",
      admin: false,
      owner: false,
    },
    {
      id: 328406,
      resource_state: 2,
      name: "Cyklokarpaty",
      profile_medium:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/328406/7732063/4/medium.jpg",
      profile:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/328406/7732063/4/large.jpg",
      cover_photo:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/328406/7732084/7/large.jpg",
      cover_photo_small:
        "https://dgalywyr863hv.cloudfront.net/pictures/clubs/328406/7732084/7/small.jpg",
      activity_types: [
        "Handcycle",
        "EBikeRide",
        "VirtualRide",
        "Velomobile",
        "Ride",
      ],
      activity_types_icon: "sports_bike_normal",
      dimensions: [
        "distance",
        "num_activities",
        "best_activities_distance",
        "velocity",
        "elev_gain",
        "moving_time",
      ],
      sport_type: "cycling",
      city: "",
      state: "",
      country: "Polska",
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: "cyklokarpaty",
      membership: "member",
      admin: false,
      owner: false,
    },
  ],
  ftp: 280,
  bikes: [
    {
      id: "b3008097",
      primary: false,
      name: "Giant Talon 27.5 2",
      nickname: "Giant Talon 27.5 2",
      resource_state: 2,
      retired: false,
      distance: 3777221,
      converted_distance: 3777.2,
    },
    {
      id: "b4766638",
      primary: false,
      name: "Kross B9",
      nickname: "Kross B9",
      resource_state: 2,
      retired: false,
      distance: 25949,
      converted_distance: 25.9,
    },
    {
      id: "b3008090",
      primary: false,
      name: "Scott CR1 20",
      nickname: "Scott CR1 20",
      resource_state: 2,
      retired: false,
      distance: 2851957,
      converted_distance: 2852,
    },
    {
      id: "b4811935",
      primary: true,
      name: "Scott Scale 935",
      nickname: "Scott Scale 935",
      resource_state: 2,
      retired: false,
      distance: 20817052,
      converted_distance: 20817.1,
    },
    {
      id: "b7427246",
      primary: false,
      name: "Specialized Tarmac disc",
      nickname: "Specialized Tarmac disc",
      resource_state: 2,
      retired: false,
      distance: 5536581,
      converted_distance: 5536.6,
    },
    {
      id: "b4431805",
      primary: false,
      name: "tacx FLOW SMART",
      nickname: "tacx FLOW SMART",
      resource_state: 2,
      retired: false,
      distance: 3954027,
      converted_distance: 3954,
    },
    {
      id: "b8051148",
      primary: false,
      name: "Wahoo Kickr Core",
      nickname: "Wahoo Kickr Core",
      resource_state: 2,
      retired: false,
      distance: 4226008,
      converted_distance: 4226,
    },
  ],
  shoes: [],
  is_winback_via_upload: false,
  is_winback_via_view: false,
};
